plugins {
    id 'com.android.application'
}
android {
    namespace 'com.example.himoviehook'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.himoviehook"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    compileOnly 'de.robv.android.xposed:api:82'
}
